export interface CategoryMeta {
  id: string;
  slug: string;
  titleAr: string;
  titleEn: string;
  descAr: string;
  descEn: string;
}

export const CATEGORY_META: CategoryMeta[] = [
  { id: 'Sex Toys', slug: 'sex-toys', titleAr: 'ألعاب جنسية في لبنان | العاب جنسيه | متجر فيكسا', titleEn: 'Sex Toys Lebanon | #1 Adult Store | Vexa Store', descAr: '500+ لعبة جنسية وزوجية في لبنان تُشحن بسرية تامة — صناديق مغلقة بدون شعار. هزازات، ديلدو، ألعاب رجالية والمزيد. توصيل في نفس اليوم في بيروت، دفع عند الاستلام. خصوصيتك مضمونة.', descEn: '500+ sex toys shipped discreetly across Lebanon — plain sealed boxes, no logo. Vibrators, Dildos, Male Toys & more. Same-day Beirut delivery, cash on delivery. Your privacy is guaranteed.' },
  { id: 'Sex Toys', slug: 'adult-toys', titleAr: 'ألعاب للكبار في لبنان | العاب جنسيه في لبنان | متجر فيكسا', titleEn: 'Adult Toys in Lebanon | #1 Discreet Delivery | Vexa Store', descAr: 'اشتر ألعاب للكبار في لبنان — 500+ منتج. العاب جنسيه في لبنان بتغليف سري 100% بدون شعار. توصيل في نفس اليوم في بيروت. دفع عند الاستلام. خصوصيتك مضمونة.', descEn: 'Shop adult toys in Lebanon — 500+ products with 100% discreet delivery. Plain sealed boxes, no logo, no receipt visible. Same-day Beirut delivery, cash on delivery. Your privacy is guaranteed.' },
  { id: 'Vibrators', slug: 'vibrators', titleAr: 'هزازات فاخرة في لبنان | متجر فيكسا', titleEn: 'Vibrators Lebanon | Vexa Store', descAr: 'تسوّق 100+ هزاز في لبنان — نحيل، عصا، أرنب ونقطة G. سيليكون آمن للجسم. توصيل سري في نفس اليوم في بيروت. دفع عند الاستلام. خصوصيتك مضمونة.', descEn: 'Shop 100+ vibrators in Lebanon — bullet, wand, rabbit & G-spot styles. Body-safe silicone. Same-day discreet delivery in Beirut. Cash on delivery. Your privacy is guaranteed.' },
  { id: 'Male Toys', slug: 'male-toys', titleAr: 'ألعاب رجالية في لبنان | متجر فيكسا', titleEn: 'Male Toys Lebanon | Vexa Store', descAr: 'تسوّق ألعاب رجالية في لبنان — أدوات استمناء، مضخات قضيب، حلقات وأكثر. توصيل سري في صندوق عادي في بيروت. دفع عند الاستلام. سريع وخاص.', descEn: 'Shop male sex toys in Lebanon — masturbators, penis pumps, cock rings & more. Discreet plain-box delivery in Beirut. Cash on delivery. Fast & 100% private.' },
  { id: 'Dildos', slug: 'dildos', titleAr: 'ديلدو في لبنان | سيليكون آمن | متجر فيكسا', titleEn: 'Dildo in Lebanon | Body-Safe Silicone | Vexa Store', descAr: 'اشتر ديلدو في لبنان — سيليكون آمن وواقعي بأحجام وأشكال متعددة. توصيل سري في نفس اليوم في بيروت. دفع عند الاستلام. تغليف 100% خاص بدون شعار.', descEn: 'Buy a dildo in Lebanon — body-safe silicone & realistic styles in every size. Same-day discreet delivery in Beirut. Cash on delivery. 100% private plain packaging. No logo.' },
  { id: 'Lingerie', slug: 'lingerie', titleAr: 'لانجري فاخر في لبنان | متجر فيكسا', titleEn: 'Lingerie Lebanon | Vexa Store', descAr: 'لانجري فاخر في لبنان — دانتيل، ساتان، بدلات جسم وأطقم حميمية أنيقة للنساء. توصيل سري وسريع في بيروت. دفع عند الاستلام.', descEn: 'Luxury lingerie in Lebanon — lace bras, satin sets, bodysuits & intimate kits for women. Elegant & sexy styles. Discreet fast delivery in Beirut. Cash on delivery.' },
  { id: 'BDSM', slug: 'bdsm', titleAr: 'BDSM في لبنان | ألعاب للأزواج | متجر فيكسا', titleEn: 'BDSM in Lebanon | Restraints, Blindfolds & More | Vexa Store', descAr: 'تسوّق BDSM في لبنان للمبتدئين والمحترفين — قيود، عصابات عين، مجاديف، ريش، أطقم أزواج وأكثر. مواد آمنة. توصيل سري في بيروت. دفع عند الاستلام.', descEn: 'Shop BDSM in Lebanon — restraints, blindfolds, paddles, feathers, couples kits & more. Beginner to advanced. Body-safe materials. Discreet delivery in Beirut. Cash on delivery.' },
  { id: 'Holiday Collection', slug: 'holiday-collection', titleAr: 'مجموعة الأعياد | متجر فيكسا لبنان', titleEn: 'Holiday Collection | Vexa Store Lebanon', descAr: 'هدايا رومانسية وأطقم مميزة في لبنان — مثالية لعيد الحب، الذكرى السنوية والمناسبات الخاصة. تغليف هدايا سري وسريع في بيروت.', descEn: 'Romantic gift sets & holiday bundles in Lebanon — perfect for Valentine's, anniversaries & special occasions. Discreet gift delivery in Beirut. Cash on delivery.' },
  { id: 'New Arrivals', slug: 'new-arrivals', titleAr: 'وصل حديثاً | متجر فيكسا لبنان', titleEn: 'New Arrivals | Vexa Store Lebanon', descAr: 'اكتشف أحدث الألعاب الزوجية والمنتجات الحميمية في متجر فيكسا لبنان — هزازات، ديلدو، لانجري وأكثر. يُشحن بسرية تامة في بيروت.', descEn: 'Discover the latest sex toys & intimate products at Vexa Store Lebanon — vibrators, dildos, lingerie & more. New stock weekly. Discreet delivery in Beirut.' },
  { id: 'Butt Plugs', slug: 'butt-plugs', titleAr: 'سدادة شرجية في لبنان | متجر فيكسا', titleEn: 'Butt Plugs Lebanon | Vexa Store', descAr: 'تسوّق سدادات شرجية في لبنان — سيليكون، معدن، زجاج وأنواع مهتزة لجميع مستويات الخبرة. مريحة وآمنة. توصيل سري في بيروت.', descEn: 'Shop butt plugs in Lebanon — silicone, metal, glass & vibrating styles for all experience levels. Safe & body-friendly. Discreet delivery in Beirut. Cash on delivery.' },
  { id: 'Anal Toys', slug: 'anal-toys', titleAr: 'ألعاب شرجية في لبنان | متجر فيكسا', titleEn: 'Anal Toys Lebanon | Vexa Store', descAr: 'تسوّق ألعاب شرجية في لبنان — سدادات، خرز، مدلّكات بروستاتا وأكثر. مواد آمنة للجسم. خيارات للمبتدئين. توصيل سري في بيروت وكل لبنان.', descEn: 'Explore anal toys in Lebanon — plugs, beads, prostate massagers & more. All body-safe materials. Beginner-friendly options available. Discreet delivery in Beirut & all Lebanon.' },
  { id: 'Bondage', slug: 'bondage', titleAr: 'Bondage في لبنان | متجر فيكسا', titleEn: 'Bondage Lebanon | Vexa Store', descAr: 'تسوّق أدوات Bondage في لبنان — قيود، أصفاد، حبال، عوارض وأكثر. مجموعات للمبتدئين والمحترفين. توصيل سري في صندوق عادي في بيروت.', descEn: 'Shop bondage toys in Lebanon — restraints, handcuffs, ropes, spreader bars & more. Beginner to advanced kits. Discreet plain-box delivery in Beirut. Cash on delivery.' },
  { id: 'Sex Dolls', slug: 'sex-dolls', titleAr: 'دمى جنسية في لبنان | متجر فيكسا', titleEn: 'Sex Dolls Lebanon | Vexa Store', descAr: 'دمى جنسية واقعية في لبنان — سيليكون وTPE بتصميم حيوي. توصيل سري وسريع في كل لبنان. دفع عند الاستلام. تغليف سري مضمون.', descEn: 'Realistic sex dolls in Lebanon — silicone & TPE with lifelike design. Discreet fast delivery across all Lebanon. Cash on delivery. Plain sealed packaging guaranteed.' },
  { id: 'Strap Ons', slug: 'strap-ons', titleAr: 'أحزمة Strap-on في لبنان | متجر فيكسا', titleEn: 'Strap-ons Lebanon | Vexa Store', descAr: 'تسوّق أحزمة Strap-on في لبنان — أحزمة قابلة للتعديل، ديلدو واقعي وأطقم للأزواج. توصيل سري وسريع في بيروت. دفع عند الاستلام.', descEn: 'Shop strap-ons & harnesses in Lebanon — adjustable harnesses, realistic dildos & couples kits. Discreet fast delivery in Beirut. Cash on delivery available.' },
  { id: 'Kegel Balls', slug: 'kegel-balls', titleAr: 'كرات كيجل في لبنان | متجر فيكسا', titleEn: 'Kegel Balls Lebanon | Vexa Store', descAr: 'تسوّق كرات كيجل وكرات بن وا في لبنان — تقوية عضلات قاع الحوض وتعزيز المتعة. سيليكون آمن للجسم. توصيل سري في بيروت.', descEn: 'Shop kegel balls & Ben Wa balls in Lebanon — strengthen pelvic floor & enhance pleasure. Body-safe silicone options. Discreet delivery in Beirut. Cash on delivery.' },
  { id: 'Sexual Enhancers', slug: 'sexual-enhancers', titleAr: 'معززات جنسية في لبنان | متجر فيكسا', titleEn: 'Sexual Enhancers Lebanon | Vexa Store', descAr: 'معززات جنسية في لبنان — بخاخات تأخير، جل إثارة، معززات الرغبة وأكثر. مُختبرة سريرياً وآمنة. توصيل سري وسريع في بيروت. دفع عند الاستلام.', descEn: 'Sexual enhancers in Lebanon — delay sprays, arousal gels, libido boosters & more. Clinically tested & body-safe. Discreet fast delivery in Beirut. Cash on delivery.' },
  { id: 'Penis Pumps', slug: 'penis-pumps', titleAr: 'مضخات القضيب في لبنان | متجر فيكسا', titleEn: 'Penis Pumps Lebanon | Vexa Store', descAr: 'تسوّق مضخات القضيب في لبنان — يدوية وكهربائية بجودة طبية. لتعزيز الأداء والانتصاب. توصيل سري وسريع في بيروت. دفع عند الاستلام.', descEn: 'Shop penis pumps in Lebanon — manual & electric, medical-grade quality. Enhance performance & erection. Discreet fast delivery in Beirut. Cash on delivery available.' },
  { id: 'Cock Rings', slug: 'cock-rings', titleAr: 'حلقات القضيب في لبنان | متجر فيكسا', titleEn: 'Cock Rings Lebanon | Vexa Store', descAr: 'تسوّق حلقات قضيب في لبنان — سيليكون طبي، معدن وأنواع مهتزة لتعزيز المتعة والأداء. مواد آمنة. توصيل سري في بيروت. دفع عند الاستلام.', descEn: 'Shop cock rings in Lebanon — medical silicone, metal & vibrating styles for enhanced pleasure & performance. Body-safe. Discreet delivery in Beirut. Cash on delivery.' },
  { id: 'Masturbators', slug: 'masturbators', titleAr: 'أدوات الاستمناء في لبنان | متجر فيكسا', titleEn: 'Masturbators Lebanon | Vexa Store', descAr: 'أدوات استمناء رجالية فاخرة في لبنان — ملمس واقعي، أنماط متعددة وأكثر. توصيل سري في بيروت وكل لبنان. دفع عند الاستلام.', descEn: 'Premium male masturbators in Lebanon — realistic texture, multiple modes, pocket-style & more. Discreet delivery in Beirut & all Lebanon. Cash on delivery.' },
  { id: 'Chastity', slug: 'chastity', titleAr: 'أجهزة العفة في لبنان | متجر فيكسا', titleEn: 'Chastity Devices Lebanon | Vexa Store', descAr: 'تسوّق أجهزة عفة في لبنان — معدن، سيليكون وبلاستيك للأزواج واللعب المنفرد. توصيل سري في صندوق عادي في بيروت. دفع عند الاستلام.', descEn: 'Chastity cages & devices in Lebanon — metal, silicone & plastic styles for couples & solo play. Discreet plain-box delivery in Beirut. Cash on delivery.' },
  { id: 'Sex Machines', slug: 'sex-machines', titleAr: 'ماكينات الجنس في لبنان | متجر فيكسا', titleEn: 'Sex Machines Lebanon | Vexa Store', descAr: 'ماكينات جنس أوتوماتيكية في لبنان — اهتزاز ودفع للاستخدام المنفرد والأزواج. قوية وقابلة للشحن. توصيل سري في كل لبنان. دفع عند الاستلام.', descEn: 'Automatic sex machines in Lebanon — thrusting & vibrating for solo & couples play. Powerful & rechargeable. Discreet delivery across Lebanon. Cash on delivery.' },
  { id: 'Lubricants', slug: 'lubricants', titleAr: 'مواد التشحيم في لبنان | متجر فيكسا', titleEn: 'Lubricants Lebanon | Vexa Store', descAr: 'مواد تشحيم مائية وسيليكون في لبنان — آمنة للجسم، طويلة الأمد ولطيفة على البشرة. متوافقة مع جميع الألعاب. توصيل سري وسريع في بيروت.', descEn: 'Water-based & silicone lubricants in Lebanon — body-safe, long-lasting & skin-friendly. Compatible with all toys. Discreet fast delivery in Beirut. Cash on delivery.' },
  { id: 'Poppers', slug: 'poppers', titleAr: 'بوبرز في لبنان | متجر فيكسا', titleEn: 'Poppers Lebanon | Vexa Store', descAr: 'اشتر بوبرز أونلاين في لبنان — Rush، Amsterdam، Jungle Juice وماركات أكثر. توصيل سري وسريع في بيروت وكل لبنان. دفع عند الاستلام.', descEn: 'Buy poppers online in Lebanon — Rush, Amsterdam, Jungle Juice & more top brands. Discreet fast delivery in Beirut & all Lebanon. Cash on delivery available.' },
];

export const SLUG_TO_CATEGORY: Record<string, string> = Object.fromEntries(
  CATEGORY_META.map(c => [c.slug, c.id])
);

export const CATEGORY_TO_SLUG: Record<string, string> = Object.fromEntries(
  CATEGORY_META.map(c => [c.id, c.slug])
);

export function getCategoryMeta(slug: string): CategoryMeta {
  return CATEGORY_META.find(c => c.slug === slug) || CATEGORY_META[0];
}

